---
title: "RESEARCH"
---

My research has mainly focused on the development of tools and methodologies pertaining to the classification and clustering analysis realms, with a specific attention to their density-based formulation. I have been lucky enough to work on this topic both from a parametric (model-based) and nonparametric (modal) standpoint and both from a theoretical and from a more application-motivated point of view. <br>
Currently I am working under the supervision of [Prof. Brendan Murphy](https://people.ucd.ie/brendan.murphy) on the development of latent variable models to summarize the information recorded in high-dimensional, dependent and complex-structured data. Moreover, within the VistaMilk project, I am actively collaborating with animal scientists to improve prediction performances of milk-related features. 

### INTEREST
* Model-based clustering 
* Modal clustering 
* Density estimation
* Latent variable models
* Dimensionality reduction 
* Computational statistics
* Chemometrics


### PUBLICATIONS
#### Preprints and Submitted Papers
* **Casa, A.**, Cappozzo, A. & Fop, M. (2021+) <br>
*Group-wise shrinkage for multiclass Gaussian Graphical Models*. <br>
[(arXiv)](https://arxiv.org/pdf/2105.07935.pdf)
* **Casa, A.**, O'Callaghan, T.F. & Murphy, T.B. (2021+). <br>
*Parsimonious Bayesian Factor Analysis for modelling latent structures in spectroscopy data*. <br>
[(arXiv)](https://arxiv.org/pdf/2101.12499.pdf)

#### Articles 
* Stakia, A., Dorigo, T., Banelli, G., Bortoletto, D., **Casa, A.**, [...], Vischia, P. & Weiler, A. (2021+) <br>
*Advanced multi-variate analysis methods for new physics searches at the Large Hadron Collider*. <br>
Reviews in Physics (In press)
[(arXiv)](https://arxiv.org/pdf/2105.07530.pdf)
* Frizzarin, M., Bevilacqua, A., [...], Stefanucci, M. & **Casa, A.** (2021) <br>
*Mid infrared spectroscopy and milk quality traits: a data analysis competition at the “International Workshop on Spectroscopy and Chemometrics 2021”* <br>
Chemometrics and Intelligent Laboratory Systems (In press) [(arXiv)](https://arxiv.org/pdf/2107.02906.pdf)
* **Casa, A.**, Bouveyron, C., Erosheva, E. & Menardi, G. (2021). <br>
*Co-clustering of time-dependent data via the Shape Invariant Model*. <br>
Journal of Classification [(Link)](https://link.springer.com/article/10.1007%2Fs00357-021-09402-8)
* Frizzarin, M., O'Callaghan, T.F., Murphy, T.B., Hennessy, D. & **Casa, A.** (2021). <br>
*Application of machine learning methods to milk mid-infrared spectra for discrimination of cows milk from pasture or total mixed ration diets*. <br>
Journal of Dairy Science [(Link)](https://www.sciencedirect.com/science/article/pii/S0022030221009097?dgcid=author).
* **Casa, A.** & Menardi, G. (2021). <br> 
*Nonparametric semi-supervised classification with application to signal detection in high energy physics.* <br>
Statistical Methods & Applications [(Link)](https://doi.org/10.1007/s10260-021-00585-3)
* **Casa, A.**, Fop, M. & Murphy, T.B. (2021). <br>
*Contributed Discussion on "Centered partition processes: informative priors for clustering" by Paganin, S., Herring, A.H., Olshan, A.F. & Dunson, D.B.* <br>
Bayesian Analysis, 16(1), 301-370.
[(Link)](https://projecteuclid.org/journals/bayesian-analysis/volume-16/issue-1/Centered-Partition-Processes-Informative-Priors-for-Clustering-with-Discussion/10.1214/20-BA1197.full#abstract)
* Frizzarin, M., Gormley, I.C., Berry, D.P., Murphy, T.B., **Casa, A.**, Lynch, A. & McParland, S. (2021). <br>
*Predicting cow milk quality traits from routinely available milk spectra using statistical machine learning methods.* <br>
Journal of Dairy Science, 104(7), 7438–7447. [(Link)](https://doi.org/10.3168/jds.2020-19576) 
* **Casa, A.**, Scrucca, L. & Menardi, G. (2021). <br>
*Better than the best? Answers via model ensemble in density-based clustering.* <br>
Advances in Data Analysis and Classification, 15, 599-623. 
[(Link)](https://link.springer.com/article/10.1007/s11634-020-00423-6)
* **Casa, A.**, Chacon, J.E. & Menardi, G. (2020). <br>
*Modal clustering asymptotics with applications to bandwidth selection.* <br>
Electronic Journal of Statistics, 14(1), 835-856. [(Link)](https://projecteuclid.org/download/pdfview_1/euclid.ejs/1581130993)
[(arXiv)](https://arxiv.org/abs/1901.07300)
* **Casa, A.** (2018).<br>
*On the choice of the weight function for the integrated likelihood.* <br>
SM Journal of Biometrics & Biostatistics, 3(3), 1033.
[(Link)](https://www.jsmcentral.org/sm-biometrics-biostatistics/fulltext_smjbb-v3-1033.pdf)

#### Book Chapters 
* Cabassi A., **Casa, A.**, Farcomeni, A., Fontana, M. & Russo, M. (2018). <br>
*Three testing perspectives on connectome data.* <br>
Studies in Neural Data Science, Springer Volume ‘Proceedings in Mathematics & Statistics’, ISBN-9783030000394.

#### Refereed Conference Proceedings
* Cappozzo, A., **Casa, A.** & Fop, M. (2021). <br>
*Model-based clustering with sparse matrix mixture models*. <br>
CLADAG 2021 - Book of Abstract and Short Papers. DOI: 10.36253/978-88-5518-340-6
* Cappozzo, A., **Casa, A.** & Fop, M. (2021). <br>
*Penalized model-based clustering for three-way data structures.* <br>
Book of short papers - SIS 2021. ISBN 978-88-9192-736-1
* **Casa, A.**, O'Callaghan, T.F. & Murphy, T.B. (2021). <br>
*Parsimonious modelling of spectroscopy data via a Bayesian latent variables approach.* <br>
Book of short papers - SIS 2021. ISBN 978-88-9192-736-1
* **Casa, A.**, Chacon, J.E. & Menardi, G. (2019).<br>
*Asymptotics for bandwidth selection in nonparametric clustering.* <br>
CLADAG 2019 - Book of Short Papers. ISBN: 978-88-8317-108-6
* **Casa, A.** & Menardi, G. (2019).<br>
*Nonparametric Semisupervised Classification and Variable Selection for New Physics Searches.* <br> 
EMS 2019 - Program and Book of Abstracts.
* Pascali, G., **Casa, A.** & Menardi, G. (2019). <br>
*Co-clustering TripAdvisor data for personalized recommendations.* <br>
Proceedings of the Conference of the Italian Statistical Society. ISBN: 978-88-9191-51-0
* **Casa, A.**, Scrucca, L. & Menardi, G. (2018).<br>
*Averaging via stacking in model-based clustering.* <br>
Book of Abstracts of the 4th International Workshop on Model-Based Clustering and Classification.
* **Casa, A.**, Scrucca, L. & Menardi, G. (2018).<br>
*On the selection uncertainty in parametric clustering.* <br>
Book of Abstracts of the European Conference on Data Analysis.
* **Casa, A.**, Chacon, J.E. & Menardi, G. (2018). <br>
*On the choice of an appropriate bandwidth for modal clustering.* <br>
Proceedings of the Conference of the Italian Statistical Society. ISBN: 978-88-9191-023-3.
* **Casa, A.**, Chacon, J.E. & Menardi, G. (2018).<br>
*Clustering-oriented selection of the amount of smoothing in kernel density estimation.* <br>
Book of Abstracts ISNPS 2018. ISBN: 978-88-61970-00-7.
* **Casa, A.** & Menardi, G. (2017).<br>
*Signal detection in high energy physics via a semisupervised nonparametric approach.* <br>
Proceedings of the Conference of the Italian Statistical Society. ISBN: 978-88-6453-521-0.
* **Casa, A.** & Menardi, G. (2017). <br>
*Nonparametric semi-supervised classification with application to signal detection in high energy physics.* <br> Book of Abstracts of the International Federation of Classification Societies (IFCS).


