---
title: 'Talks'
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

- *High-dimensional covariance estimation via sparse pairwise composite likelihood* (March, 2025) <br> DSS Statistics Seminar, Sapienza Università di Roma [seminar]

- *Adaptive functional regression for locally heterogeneous spectroscopic data* (December, 2024) <br> 18th International Joint Congerence CFE-CMStatistics, London [invited]

- *Sparse model-based clustering of three-way data via lasso-type penalties* (July, 2024) <br> Working Group of Model-Based Clustering, University of Bologna - Bertinoro (FC)  [invited]

- *Sparse partial membership models with applications in food science* (June, 2024) <br> 52nd Scientific meeting of the Italian Statistical Society, Bari [invited]

- *Partial membership models for high-dimensional spectroscopy data* (September, 2023) <br> CLADAG - Classification and Data Analysis Group, Salerno [invited]

- *Regularization strategies for partial membership models* (July, 2023) <br> Working Group of Model-Based Clustering, Carnegie Mellon University - Pittsburgh [invited]

- *Parsimonious modelling of spectroscopy data via a Bayesian latent variables approach* (May, 2023) <br> Mathematics for Data Science, AI and ML Seminar series, University of Trento [seminar]

- *Sparse covariance estimation via sparse composite likelihood* (February, 2023) <br>     UCD Working Group on Statistical Learning, Dublin [seminar]

- *Unveiling patterns in spectroscopy data via a Bayesian latent variables approach* (December, 2022) <br> International Conference of the ERCIM WG - CMStatistics 2022, London [invited]

- *Parsimonious Bayesian factor analysis with application to spectroscopy data* (December, 2022) <br> Workshop on statistical learning and econometrics, Bolzano [invited]

-   *Penalized matrix-variate model-based clustering*
    (September, 2022) <br> European Conference on Data Analysis 2022 - ECDA 2022, Naples [invited]

-   *Model ensemble in density-based clustering*
    (August, 2022) <br> 24th International conference 
    on Computational Statistics - COMPSTAT 2022, Bologna [invited]

-   *Group-wise penalized estimation schemes in model-based clustering*
    (June 2022) <br> 51st Scientific
    Meeting of the Italian Statistical Society, Caserta [invited]

-   *Co-clustering of time-dependent data via the Shape Invariant Model*
    (February 2022) <br> Trinity
    College Dublin Statistics Seminar Series, online [seminar]

-   *Model-based co-clustering of multivariate time-dependent data*
    (December 2021) <br> 14th
    International Conference of the ERCIM WG - CMStatistics 2021, online
    [invited]

-   *Sparse matrix-variate model-based clustering via penalized estimation* (October 2021) <br> Working Group on Model-Based Clustering, Athens [short presentation]

-   *Model-based clustering with sparse matrix mixture models*
    (September 2021) <br> CLADAG -
    Classification and Data Analysis Group, online [contributed]

-   *Parsimonious modelling of spectroscopy data via a Bayesian latent      variables approach* (June 2021)
    <br> 50th Scientific Meeting of the Italian Statistical Society,
    online [contributed]

-   *Parsimonious Bayesian Factor Analysis with application to milk spectroscopy data* (May 2021)
    <br> 41st Conference on Applied Statistics in Ireland, online
    [contributed]

-   *Parsimonious Bayesian Factor Analysis for modelling latent structures in spectroscopy data*
    (February 2021) <br> UCD
    Working Group on Statistical Learning, online [seminar]

-   *Better than the best? Blending models and approaches in density-based clustering* (February 2020) <br> UCD Working Group on Statistical Learning, Dublin [seminar]

-   *Asymptotics for bandwidth selection in nonparametric clustering*
    (September 2019) <br> CLADAG -
    Classification and Data Analysis Group, Cassino [invited]

-   *Nonparametric semisupervised classification and variable selection for new physics searches* (July 2019) <br> European Meeting of Statisticians, Palermo [invited]

-   *Co-clustering of time-dependent data*
    (July 2019) <br> Working Group
    on Model-Based Clustering, Wien [poster]

-   *Averaging via stacking in model-based clustering*
    (September 2018) <br> Workshop
    Advanced Statistics for Physics Discovery, Padova [short
    presentation]

-   *Averaging via stacking in model-based clustering*
    (September 2018) <br>
    MBC2 2018 Workshop on Model-Based Clustering and Classification,
    Catania [poster]

-   *On the selection uncertainty in parametric clustering*
    (July 2018) <br> ECDA 2018 European
    Conference on Data Analysis, Paderborn [contributed]

-   *On the choice of an appropriate bandwidth for modal clustering*
    (June 2018) <br> SIS 2018 49th
    Scientific meeting of the Italian Statistical Society, Palermo
    [contributed]

-   *Clustering-oriented selection of the amount of smoothing in kernel
    density estimation* (June 2018) <br>
    4th Conference of the International Society for Nonparametric
    Statistics, Salerno [contributed]

-   *Signal detection in high energy physics via a semisupervised
    nonparametric approach* (June 2017). <br> SIS 2017 Intermediate conference of the Italian Statistical Society, Florence [contributed]
