---
title: ""
output:
  html_document:
    self_contained: false
    always_allow_html: true
---
```{=html}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">
<style>
  .navbar {
    background-color: #f8f8f8;
    border: none;
    padding: 15px 20px;
    font-size: 17px;
  }
  .navbar a { color: #555555; margin-right: 15px; text-decoration: none; }
  .navbar-brand { font-weight: bold; font-size: 24px !important; }

  /* New styles for main content */
  div[style*="margin-top: 50px;"] {
    font-size: 18px;
  }

  div[style*="margin-top: 30px;"] h3 {
    font-size: 26px;
  }
</style>
<!-- Navbar -->
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Alessandro Casa</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="bio.html">Short bio</a></li>
        <li><a href="research.html">Publications</a></li>
        <li><a href="teaching.html">Teaching & Software</a></li>
        <li><a href="contact.html">Contact</a></li>
      </ul>
    </div>
  </div>
</div>
```

<div style="margin-top: 50px;">



### From academic year 2024/25
#### Free University of Bozen-Bolzano 
* Statistical Methods for Business Analysis - Lecturer (in english) <br>
MSc in Data Analytics for Economics and Management, MSc Entrepreneurship and Innovation
* Research methods and experimental design - Lecturer (in english) <br> 
MSc in Tourism Management
* Statistics for Tourism, Sport and Event Management - Lecturer (in italian) <br>
BSc in Tourism, Sports and Event Management

### Academic year 2023/24
#### University of Bergamo 
* Statistics - Lecturer (in italian)
<br>
BSc in Ingegneria Meccanica
#### Free Univeristy of Bozen-Bolzano
* Statistics for Tourism, Sport and Event Management - Teaching assistant (in italian) <br>
BSc in Tourism, Sports and Event Management

### Academic year 2022/23
#### Free University of Bozen-Bolzano
* High-dimensional Econometric Methods for Big Data - Lecturer (in english) <br> 
PhD in Economics and Finance 
* Statistical Methods for Business Analysis - Lecturer (in english) <br>
MSc in Entrepreneurship and Innovation 
* Statistics for Tourism, Sport and Event Management - Teaching assistant (in italian) <br>
BSc in Tourism, Sports and Event Management
* Statistics - Teaching assistant (in italian) <br>
BSc in Economics and Management

### Academic year 2021/22
#### Free University of Bozen-Bolzano
* Statistical Methods for Business Analysis - Lecturer <br>
MSc in Entrepreneurship and Innovation 

### Previous experiences
#### University College Dublin 
* STAT20060, Statistics & Probability - Lecturer  <br>
Level 2 - Academic year 2019/2020
* STAT20060, Statistics & Probability - Teaching assistant <br> 
Level 2 - Academic year 2019/2020
* STAT30270/40590, Statistical Machine Learning - Teaching assistant <br>
Level 3 - Academic year 2019/2020

#### University of Padova
* *Bike sharing in Paris: a case study* (in italian). Specialist lecture during the class Statistica Iterazione <br>
Master degree - Academic year 2018/2019

&nbsp;

## Software
Most of my code is available on my [Github page](https://github.com/AlessandroCasa).

</div>